import 'dart:convert';
import 'dart:io';

class Autogenerated {
  final String? createdBy;
  final int? createdAt;
  final String? lastModifiedBy;
  final int? lastModifiedAt;
  final String? name;
  final String? description;
  final String? controllerId;
  final String? updateStatus;
  final String? securityToken;
  final bool? requestAttributes;
  final Links? links;

  Autogenerated({
    this.createdBy,
    this.createdAt,
    this.lastModifiedBy,
    this.lastModifiedAt,
    this.name,
    this.description,
    this.controllerId,
    this.updateStatus,
    this.securityToken,
    this.requestAttributes,
    this.links,
  });

  factory Autogenerated.fromJson(Map<String, dynamic> json) => Autogenerated(
      createdBy: json["createdBy"],
      createdAt: json["createdAt"],
      lastModifiedBy: json["lastModifiedBy"],
      lastModifiedAt: json["lastModifiedAt"],
      name: json["name"],
      description: json["description"],
      controllerId: json["controllerId"],
      updateStatus: json["updateStatus"],
      securityToken: json["securityToken"],
      requestAttributes: json["requestAttributes"],
      links: json["_links"] == null ? null : Links.fromJson(json["_links"]));

  Map<String, dynamic> toJson() => {
        "createdBy": createdBy,
        "createdAt": createdAt,
        "lastModifiedBy": lastModifiedBy,
        "lastModifiedAt": lastModifiedAt,
        "name": name,
        "description": description,
        "controllerId": controllerId,
        "updateStatus": updateStatus,
        "securityToken": securityToken,
        "requestAttributes": requestAttributes,
        "_links": links?.toJson(),
      };
}

class Links {
  final Actions? self;
  final Actions? assignedDs;
  final Actions? installedDs;
  final Actions? attributes;
  final Actions? actions;
  final Actions? metadata;

  Links({
    this.self,
    this.assignedDs,
    this.installedDs,
    this.attributes,
    this.actions,
    this.metadata,
  });

  factory Links.fromJson(Map<String, dynamic> json) => Links(
        self: json["self"] == null ? null : Actions.fromJson(json["self"]),
        assignedDs: json["assignedDS"] == null
            ? null
            : Actions.fromJson(json["assignedDS"]),
        installedDs: json["installedDS"] == null
            ? null
            : Actions.fromJson(json["installedDS"]),
        attributes: json["attributes"] == null
            ? null
            : Actions.fromJson(json["attributes"]),
        actions:
            json["actions"] == null ? null : Actions.fromJson(json["actions"]),
        metadata: json["metadata"] == null
            ? null
            : Actions.fromJson(json["metadata"]),
      );

  Map<String, dynamic> toJson() => {
        "self": self?.toJson(),
        "assignedDS": assignedDs?.toJson(),
        "installedDS": installedDs?.toJson(),
        "attributes": attributes?.toJson(),
        "actions": actions?.toJson(),
        "metadata": metadata?.toJson(),
      };
}

class Actions {
  final String? href;

  Actions({
    this.href,
  });

  factory Actions.fromJson(Map<String, dynamic> json) => Actions(
        href: json["href"],
      );

  Map<String, dynamic> toJson() => {
        "href": href,
      };
}

// void main() {
//   // Replace with your fetched JSON data
//   // String jsonData = /* Replace with actual JSON data */;

//   // Parse the JSON data
//   final parsedData = Autogenerated.fromJson(json.decode(jsonData));

//   // Convert the parsed data to JSON string
//   final jsonString = json.encode(parsedData.toJson());

//   // Define the file path where you want to save the text file
//   final filePath = '/path/to/file.txt'; // Replace with the actual file path

//   // Write the JSON string to a text file
//   File(filePath).writeAsStringSync(jsonString);

//   print('Data written to file: $filePath');
// }